apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ccm-from-scratch
build:
  artifacts:
    - image: apricote/ccm-from-scratch-2e27e80364c4d72c4bcfa55ce828a55b
      ko: {}
manifests:
  helm:
    releases:
      - name: ccm-from-scratch
        chartPath: chart
        namespace: kube-system
