kind: Deployment
apiVersion: apps/v1
metadata:
  name: ccm-from-scratch
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccm-from-scratch
  template:
    metadata:
      labels:
        app: ccm-from-scratch
    spec:
      hostNetwork: true
      serviceAccountName: cloud-controller-manager
      tolerations:
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          operator: Exists

      containers:
        - name: ccm-from-scratch
          image: apricote/ccm-from-scratch-2e27e80364c4d72c4bcfa55ce828a55b:latest
          args:
            - --cloud-provider=hcloud-from-scratch
            - --allow-untagged-cloud
            - --leader-elect=false
            - --cluster-cidr={{ .Values.clusterCIDR }}
          env:
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: hcloud
            - name: HCLOUD_NETWORK
              valueFrom:
                secretKeyRef:
                  key: network
                  name: hcloud

            {{- if .Values.debug }}
            - name: HCLOUD_DEBUG
              value: "true"
            {{- end }}


